kind: ConfigMap
apiVersion: v1
metadata:
  name: shield-config
  namespace: kube-system
data:
  acl: |-
		# 
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: shield
  namespace: kube-system
  labels:
    k8s-app: shield
spec:
  template:
    metadata:
      labels:
        k8s-app: shield
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      hostNetwork: true
      containers:
        - name: shield
          image: alpine:3.5
